---
# file: roles/loadbalancer/tasks/main.yml

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# In this release, we upgrade HAproxy from 1.4 to 1.5 to support SSL termination.
- name: restart HAproxy
  service: name=haproxy state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'
