---
# file: roles/loadbalancer/tasks/main.yml

# In this release, we upgrade HAproxy from 1.4 to 1.5 to support SSL termination.
# So we need to trigger a failover.
- name: Pull out the node from the HAproxy cluster
  service: name={{ item }} state=stopped
  tags: before_config
  when: ansible_distribution == 'Debian'
  with_items:
    - keepalived
    - haproxy

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# Fix HAproxy options
- name: fix heat_cfn binding
command: sed '/heat_api_cfn_dead/d' -i /etc/haproxy/haproxy.cfg
  tags: before_config
- name: fix heat_cloudwatch binding
command: sed '/heat_api_cloudwatch_dead/d' -i /etc/haproxy/haproxy.cfg
  tags: before_config

- name: start HAproxy & keepalived after upgrade
  service: name={{ item }} state=started
  tags: before_config
  when: ansible_distribution == 'Debian'
  with_items:
    - keepalived
    - haproxy
