---
# file: roles/loadbalancer/tasks/main.yml

# In this release, we upgrade HAproxy from 1.4 to 1.5 to support SSL termination.
# So we need to trigger a failover.
- name: Pull out the node from the HAproxy cluster
  service: name={{ item }} state=stopped
  tags: before_config
  when: ansible_distribution == 'Debian'
  with_items:
    - keepalived
    - haproxy

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'
