---
# file: site.yml

- hosts: all
  user: jenkins
  sudo: true

- hosts: controllers
  roles:
    - controller

- hosts: loadbalancers
  roles:
    - loadbalancer

- hosts: computes
  roles:
    - compute

