---
# file: roles/compute/tasks/main.yml

# Allow rsync to access all SElinux permissions
- seboolean: name=rsync_full_access state=yes persistent=yes
  tags: before_config

# Dirty hack to upgade /usr/sbin/edeploy before actual upgrade
# and benefit of rsync with attributes feature.
# Useful when running SElinux before J.1.0.0
- name: upgrade edeploy script
  copy: src=edeploy dest=/usr/sbin/edeploy mode=0755
  tags: before_config

# Mark the nova-compute service as disabled to prevent Nova from scheduling
# any new servers on this node
- name: disable nova-compute to prevent instance scheduling
  command: nova-manage service disable {{ ansible_fqdn }} nova-compute
  tags: before_config

- name: stop openstack services
  service: name={{ item }} state=stopped
  with_items:
    - "{{ nova_compute }}"
    - "{{ ceilometer_agent_compute }}"
    - "{{ neutron_openvswitch_agent }}"
  tags: before_config

- name: stop openvswitch service
  service: name=openvswitch-switch state=stopped
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: start openvswitch service
  service: name=openvswitch-switch state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

# Cap the compute RPC API at a version that will still be understood by your Icehouse compute nodes
- ini_file: dest=/etc/nova.conf
            section=upgrade_levels
            option=compute
            value=icehouse
  tags: before_config

- name: start nova compute service
  service: name={{ nova_compute }} state=started
  tags: before_config

- name: start other openstack services
  service: name={{ item }} state=started
  with_items:
    - "{{ ceilometer_agent_compute }}"
    - "{{ neutron-openvswitch-agent }}"
  tags: before_config

- name: allow instance scheduling on the compute node
  command: nova-manage service enable {{ ansible_fqdn }} nova-compute
  tags: before_config

- name: Ensure old puppet ssl files are removed
  file: path=/var/lib/puppet/ssl state=absent
  tags: before_config

# Clean-up nova config by deleting the option, not useful anymore
- ini_file: dest=/etc/nova.conf
            section=upgrade_levels
            option=compute
  tags: after_config

- name: restart openstack services
  service: name={{ item }} state=restarted
  with_items:
    - "{{ nova_compute }}"
    - "{{ neutron_openvswitch_agent }}"
  tags: after_config
