---
# file: roles/openstack-full/tasks/main.yml

# Debian has a kernel upgrade from 3.14 to 3.16
# So we need to restart the compute nodes and migrate the instances before.
- name: migrate instances
  script: migrate.sh {{ ansible_fqdn }} {{ os_username }} {{ os_tenant_name }} {{ os_password }} {{ os_auth_url }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# RabbitMQ is upgraded in RHEL7
- name: stop rabbitmq
  service: name=rabbitmq-server state=stopped
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: start rabbitmq
  service: name=rabbitmq-server state=started
  tags: before_config
  when: ansible_distribution == 'RedHat'

# Red Hat upgrade Galera to 25.3.5-5.el7ost
- name: bootstrap mysql cluster again
  service: name=mysql-bootstrap state=restarted
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['controller'][0]

- name: start other mysql nodes
  service: name=mysqld state=restarted
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname != groups['controller'][0]

- name: allow instance scheduling on the compute node
  command: nova-manage service enable --service nova-compute --host {{ ansible_fqdn }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# after upgrade, heat-api is zombie
- name: kill heat-api process
  command: pkill -9 heat-api
  tags: before_config
  when: ansible_distribution == 'Debian'

# then, restart it
- name: start heat-api service
  service: name=heat-api state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

# HAproxy has been updated in Debian
# from 1.5~dev26-2~bpo70+1 to 1.5.4-1~bpo70+2
- name: restart HAproxy service
  service: name=haproxy state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name=sensu-client state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: restart Cinder services after upgrade
  service: name={{ item }} state=restarted
  with_items:
    - openstack-cinder-api
    - openstack-cinder-volume
  tags: after_config
  when: ansible_distribution == 'RedHat'

- name: restart apache after upgrade
  service: name=httpd state=restarted
  tags: after_config
  when: ansible_distribution == 'RedHat'
