---
# file: roles/controller/tasks/main.yml

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

# Red Hat OSP5 upgrades Icehouse to 2014.1.3
# from 2014.1.2-2.el7ost to 2014.1.3-1.el7ost
- name: restart services after upgrade
  service: name={{ item }} state=restarted
  with_items:
    - httpd
    - neutron-metering-agent
    - neutron-server
    - openstack-ceilometer-alarm-evaluator
    - openstack-ceilometer-alarm-notifier
    - openstack-ceilometer-api
    - openstack-ceilometer-collector
    - openstack-ceilometer-notification
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume
    - openstack-glance-api
    - openstack-glance-registry
    - openstack-heat-api
    - openstack-heat-api-cfn
    - openstack-heat-api-cloudwatch
    - openstack-heat-engine
    - openstack-keystone
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-conductor
    - openstack-nova-consoleauth
    - openstack-nova-scheduler
    - openstack-nova-spicehtml5proxy
    - openstack-swift-proxy
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: update keystone database
  command: keystone-manage db_sync
  tags: before_config
  when: inventory_hostname == groups['controller'][-1] and ansible_distribution == 'RedHat'

- name: update nova database
  command: nova-manage db sync
  tags: before_config
  when: inventory_hostname == groups['controller'][-1] and ansible_distribution == 'RedHat'

- name: update glance database
  command: glance-manage db_sync
  tags: before_config
  when: inventory_hostname == groups['controller'][-1] and ansible_distribution == 'RedHat'

- name: update cinder database
  command: cinder-manage db sync
  tags: before_config
  when: inventory_hostname == groups['controller'][-1] and ansible_distribution == 'RedHat'

- name: update neutron database
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  tags: before_config
  when: inventory_hostname == groups['controller'][-1] and ansible_distribution == 'RedHat'

- name: update heat database
  command: heat-manage --config-file /etc/heat/heat.conf db_sync
  tags: before_config
  when: inventory_hostname == groups['controller'][-1] and ansible_distribution == 'RedHat'


- name: restart ceilometer-agent-central managed by pacemaker
  command: pcs resource cleanup ceilometer-agent-central
  tags: before_config
  when: inventory_hostname == groups['controller'][-1] and ansible_distribution == 'RedHat'
