---
# file: roles/network/tasks/main.yml

# Stop Services
- name: stop services before upgrade
  service: name={{ item }} state=stopped
  with_items:
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-plugin-openvswitch-agent
  tags: before_config

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version=U14.04-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Ubuntu'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config

# Start Services
- name: start services after upgrade
  service: name={{ item }} state=started
  with_items:
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-plugin-openvswitch-agent
  tags: before_config
