---
# file: roles/network/tasks/main.yml

- name: stop openstack services
  service: name={{ item }} state=stopped
  with_items:
    - "{{ neutron_dhcp_agent }}"
    - "{{ neutron_l3_agent }}"
    - "{{ neutron_lbaas_agent }}"
    - "{{ neutron_metadata_agent }}"
    - "{{ neutron_metering_agent }}"
    - "{{ neutron_openvswitch_agent }}"
  tags: before_config

- name: stop openvswitch service
  service: name=openvswitch-switch state=stopped
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: start openvswitch service
  service: name=openvswitch-switch state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: start openstack services
  service: name={{ item }} state=started
  with_items:
    - "{{ neutron_dhcp_agent }}"
    - "{{ neutron_l3_agent }}"
    - "{{ neutron_lbaas_agent }}"
    - "{{ neutron_metadata_agent }}"
    - "{{ neutron_metering_agent }}"
    - "{{ neutron_openvswitch_agent }}"
  tags: before_config

- name: restart neutron l3 agent
  service: name={{ neutron_l3_agent }} state=restarted
  tags: after_config
