---
# file: roles/network/tasks/main.yml

# Dirty hack to upgade /usr/sbin/edeploy before actual upgrade
# and benefit of rsync with attributes feature.
# Useful when running SElinux before J.1.0.0
- name: upgrade edeploy script
  copy: src=edeploy dest=/usr/sbin/edeploy mode=0755
  tags: before_config

- name: stop openstack services
  service: name={{ item }} state=stopped
  with_items:
    - "{{ neutron_dhcp_agent }}"
    - "{{ neutron_l3_agent }}"
    - "{{ neutron_lbaas_agent }}"
    - "{{ neutron_metadata_agent }}"
    - "{{ neutron_metering_agent }}"
    - "{{ neutron_openvswitch_agent }}"
  tags: before_config

- name: stop openvswitch service
  service: name=openvswitch-switch state=stopped
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: start openvswitch service
  service: name=openvswitch-switch state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: start openstack services
  service: name={{ item }} state=started
  with_items:
    - "{{ neutron_dhcp_agent }}"
    - "{{ neutron_l3_agent }}"
    - "{{ neutron_lbaas_agent }}"
    - "{{ neutron_metadata_agent }}"
    - "{{ neutron_metering_agent }}"
    - "{{ neutron_openvswitch_agent }}"
  tags: before_config

- name: Ensure old puppet ssl files are removed
  file: path=/var/lib/puppet/ssl state=absent
  tags: before_config

- name: restart openstack network services
  service: name={{ item }} state=restarted
  with_items:
    - "{{ neutron_dhcp_agent }}"
    - "{{ neutron_l3_agent }}"
    - "{{ neutron_lbaas_agent }}"
    - "{{ neutron_metadata_agent }}"
    - "{{ neutron_metering_agent }}"
    - "{{ neutron_openvswitch_agent }}"
  tags: after_config
