---
# file: roles/common/tasks/main.yml

- name: be sure cinder-api is not running
  service: name=cinder-api state=stopped
  tags: api

- name: be sure cinder-scheduler is not running
  service: name=cinder-scheduler state=stopped
  tags: scheduler

- name: be sure cinder-volume is not running
  service: name=cinder-volume state=stopped
  tags: spof

- name: edeploy upgrade
  edeploy: command=upgrade version={{ version }}
  tags: edeploy

# This action should be realised on one node, since database is replicated
- name: migrate database to multi-backend
  script: cinder.sh {{ os_username }} {{ os_tenant_name }} {{ os_password }} {{ os_auth_url }}
  tags: db
  when: inventory_hostname == groups['controllers'][0]

- name: be sure cinder-api is running
  service: name=cinder-api state=started
  tags: api

- name: be sure cinder-scheduler is running
  service: name=cinder-scheduler state=started
  tags: scheduler

- name: be sure cinder-volume is running
  service: name=cinder-volume state=started
  tags: spof

- name: purge cinder config
  script: mv /etc/cinder/cinder.conf /etc/cinder/cinder.conf.1.0.0

- name: restart rabbitmq
  service: name=rabbitmq-server state=restarted
  tag: messaging

# We need to restart Glance because we upgrade RabbitMQ, and we have a small
# downtime not handled by Glance, since it does not use Oslo messaging and HA queues.
- name: restart glance api
  service: name=glance-api state=restarted
  tag: image

- name: restart glance registry
  service: name=glance-registry state=restarted
  tag: api

# In this release, we switch token backend to SQL, so we need to flush the memcache
# to avoid any token error in services
- name: restart memcached
  service: name=memcached state=restarted
  tag: cache

# In this release, Neutron L3 Agent is updated, we need to restart it. 
- name: restart neutron-l3-agent
  service: name=neutron-l3-agent state=restarted
  tag: network
