---
# file: roles/compute/tasks/main.yml

# Debian has a kernel upgrade from 3.14 to 3.16
# So we need to restart the compute nodes and migrate the instances before.
- name: migrate instances
  script: migrate.sh {{ ansible_hostname }} {{ os_username }} {{ os_tenant_name }} {{ os_password }} {{ os_auth_url }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: allow instance scheduling on the compute node
  command: nova-manage service disable --service nova-compute --host {{ ansible_hostname }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# Red Hat OSP5 upgrades Icehouse to 2014.1.3
# from 2014.1.2-2.el7ost to 2014.1.3-1.el7ost
- name: restart services after upgrade
  service: name={{ item }} state=restarted
  with_items:
    - neutron-openvswitch-agent
    - openstack-ceilometer-compute
    - openstack-nova-compute
  tags: before_config
  when: ansible_distribution == 'RedHat'
