---
# file: roles/install/tasks/main.yml

- name: stop puppet
  service: name={{ item }} state=stopped
  with_items:
    - "{{ webserver }}"
    - puppetdb
  tags: install_server

- name: synchronize eDeploy roles & metadata with upstream
  script: edeploy-sync.sh {{ edeploy_master }} {{ distro }}-{{ version }}
  tags: install_server

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: install_server

# restart jenkins and puppet because of newer versions
- name: restart jenkins and puppet
  service: name={{ item }} state=restarted
  with_items:
    - "{{ webserver }}"
    - puppetdb
    - jenkins
  tags: install_server

- name: wait jenkins is up and running
  script: jenkins-wait.sh
  tags: install_server

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name={{ item }} state=restarted
  with_items:
    - sensu-api
    - sensu-server
    - sensu-service
    - sensu-client
  tags: install_server
  when: ansible_distribution == 'Debian'
