---
# file: roles/loadbalancer/tasks/main.yml

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version=14.04-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Ubuntu'

- name: Restart the server
  shell: sleep 2s && reboot & executable=/bin/bash
  tags: before_config

- name: Wait until the machine stop
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} state=stopped
  sudo: false
  tags: before_config

- name: Wait for server to come up
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay=60
  sudo: false
  tags: before_config
