---
# file: roles/loadbalancer/tasks/main.yml

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version=14.04-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Ubuntu'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config

# Ensure some services are running after the reboot
- name: ensure Keepalived is running
  service: name=keepalived state=started
  tags: before_config
  ignore_errors: yes

- name: ensure HAproxy is running
  command: haproxy -f /etc/haproxy/haproxy.cfg
