---
# file: roles/network/tasks/main.yml

# Allow rsync to access all SElinux permissions
- seboolean: name=rsync_full_access state=yes persistent=yes
  tags: before_config

# Dirty hack to upgade /usr/sbin/edeploy before actual upgrade
# and benefit of rsync with attributes feature.
# Useful when running SElinux before J.1.0.0
- name: upgrade edeploy script
  copy: src=edeploy dest=/usr/sbin/edeploy mode=0755
  tags: before_config

- name: stop openstack services
  service: name={{ item }} state=stopped
  with_items:
    - "{{ swift_account }}"
    - "{{ swift_container }}"
    - "{{ swift_object }}"
  tags: before_config

# Ceph is upgraded in ICE
- name: stop Ceph services
  service: name=ceph state=stopped
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: Ensure old puppet ssl files are removed
  file: path=/var/lib/puppet/ssl state=absent
  tags: before_config

- name: start Ceph services
  service: name=ceph state=started
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: start openstack services
  service: name={{ item }} state=started
  with_items:
    - "{{ swift_account }}"
    - "{{ swift_container }}"
    - "{{ swift_object }}"
  tags: before_config
