---
# file: roles/network/tasks/main.yml

- name: stop openstack services
  service: name={{ item }} state=stopped
  with_items:
    - "{{ swift-account }}"
    - "{{ swift-container }}"
    - "{{ swift-object }}"
  tags: before_config

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: start openstack services
  service: name={{ item }} state=started
  with_items:
    - "{{ swift-account }}"
    - "{{ swift-container }}"
    - "{{ swift-object }}"
  tags: before_config
