---
# file: roles/install-server/tasks/main.yml

- name: ensure rsync is started
  service: name={{ rsync }} state=started
  tags: install_server

- name: stop puppet
  service: name={{ item }} state=stopped
  with_items:
    - "{{ webserver }}"
    - puppetdb
  tags: install_server

- name: synchronize eDeploy roles & metadata with upstream
  script: edeploy-sync.sh {{ edeploy_master }} {{ distro }}-{{ version }}
  tags: install_server

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: install_server

# SElinux is a new feature in I.1.3.0 but
# Upgrade from permissive to enforced is not supported.
- name: ensure SElinux is not enabled
  command: sed -i 's/enforcing/permissive/g' /etc/config-tools/global.yml
  tags: install_server
  when: ansible_distribution == 'RedHat'

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name={{ item }} state=restarted
  with_items:
    - sensu-api
    - sensu-server
    - uchiwa
    - sensu-client
  tags: install_server
  when: ansible_distribution == 'Debian'

# From I.1.2.X to I.3.0 releases, Ansible has been upgraded and because of
# this commit: https://github.com/ansible/ansible/commit/ae2d198342c9bbb691647b897b69b9d9f26522db
# we have to clean-up manually Ansible packaging by the end of install_server tag.
# If we do that during the playbook run Ansible will crash because it won't find the
# previous library code.
- name: cleanup Ansible packaging
  command: rm -rf /usr/share/ansible
  tags: install_server

# restart jenkins because of newer version
- name: restart jenkins
  script: jenkins-restart.sh
  tags: after_config
