---
# file: roles/full/tasks/main.yml
# this role is used when all services are running on the same node.

# In this release, we upgrade HAproxy from 1.4 to 1.5 to support SSL termination.
# So we need to trigger a failover.
- name: Pull out the node from the HAproxy cluster
  service: name={{ item }} state=stopped
  tags: before_config
  when: ansible_distribution == 'Debian'
  with_items:
    - keepalived
    - haproxy

- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# This release upgrades MariaDB-galera-server
- name: restart mysql
  service: name={{ item }} state=restarted
  with_items:
    - mysql
  tags: before_config

# Fix HAproxy options
- name: fix heat_cfn binding
  command: sed '/heat_api_cfn_dead/d' /etc/haproxy/haproxy.cfg
  tags: before_config
- name: fix heat_cloudwatch binding
  command: sed '/heat_api_cloudwatch_dead/d' /etc/haproxy/haproxy.cfg
  tags: before_config

- name: start HAproxy & keepalived after upgrade
  service: name={{ item }} state=started
  tags: before_config
  when: ansible_distribution == 'Debian'
  with_items:
    - keepalived
    - haproxy

# In this release, heat-engine is no more SPOF
- name: stop heat-engine from pacemaker
  command: crm resource stop heat-engine
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: remove heat-engine from pacemaker
  command: crm configure delete heat-engine
  tags: after_config
  when: inventory_hostname == groups['full'][-1]
