---
# file: roles/install/tasks/main.yml

- name: synchronize eDeploy roles & metadata with upstream
  script: edeploy-sync.sh {{ edeploy_master }} D7-{{ version }}
  tags: edeploy_sync
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config 
  when: ansible_distribution == 'Debian'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config
