---
# file: roles/controller/tasks/main.yml

# Stop some upgraded services before
- name: stop heat-api, nova-api and neutron-server
  service: name={{ item }} state=stopped
  with_items:
    - nova-api
    - neutron-server
    - heat-api
  tags: before_config

- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# This release upgrades MariaDB-galera-server
- name: restart mysql
  service: name={{ item }} state=restarted
  with_items:
    - mysql
  tags: before_config

# In this release, heat-engine is no more SPOF
- name: stop heat-engine from pacemaker
  command: crm resource stop heat-engine
  tags: before_config
  when: inventory_hostname == groups['full'][-1]

# Wait a bit that the resource is really deleted
- name: Wait some time that Pacemaker resource is deleted
  command: /bin/sleep 5
  tags: before_config
  async: 45
  poll: 5

- name: remove heat-engine from pacemaker
  command: crm configure delete heat-engine
  tags: before_config
  when: inventory_hostname == groups['full'][-1]

# Restart some services after upgrade
- name: restart some services after eDeploy upgrade
  service: name={{ item }} state=restarted
  with_items:
    - nova-api
    - neutron-server
    - heat-api
    - neutron-plugin-openvswitch-agent
  tags: after_config
