---
# file: roles/controller/tasks/main.yml

- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# This release upgrades MariaDB-galera-server
- name: restart mysql
  service: name={{ item }} state=restarted
  with_items:
    - mysql
  tags: before_config

# In this release, heat-engine is no more SPOF
- name: stop heat-engine from pacemaker
  command: crm resource stop heat-engine
  tags: before_config
  when: inventory_hostname == groups['full'][-1]

- name: remove heat-engine from pacemaker
  command: crm configure delete heat-engine
  tags: before_config
  when: inventory_hostname == groups['full'][-1]
