---
# file: roles/loadbalancer/tasks/main.yml

- name: ensure Load-balancing services are not running to trigger a failoverg
  service: name={{ item }} state=stopped
  with_items:
    - haproxy
    - keepalived
  tags: before_config

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config

- name: ensure Load-balancing services are running
  service: name={{ item }} state=started
  with_items:
    - haproxy
    - keepalived
  tags: before_config
