---
# file: roles/network/tasks/main.yml

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

# Red Hat OSP5 upgrades Icehouse to 2014.1.3
# from 2014.1.2-2.el7ost to 2014.1.3-1.el7ost
- name: restart services after upgrade
  service: name={{ item }} state=restarted
  with_items:
    - openstack-swift-object
    - openstack-swift-container
    - openstack-swift-account
  tags: before_config
  when: ansible_distribution == 'RedHat'

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name=sensu-client state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'
