---
# file: roles/install/tasks/main.yml

- name: stop puppet
  service: name={{ item }} state=stopped
  with_items:
    - "{{ webserver }}"
    - puppetdb
  tags: install_server

- name: synchronize eDeploy roles & metadata with upstream
  script: edeploy-sync.sh {{ edeploy_master }} {{ distro }}-{{ version }}
  tags: install_server

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: install_server

# restart puppet because of newer version
- name: restart puppet services
  service: name={{ item }} state=restarted
  with_items:
    - "{{ webserver }}"
    - puppetdb
  tags: install_server

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name={{ item }} state=restarted
  with_items:
    - sensu-api
    - sensu-server
    - sensu-service
    - sensu-client
  tags: install_server
  when: ansible_distribution == 'Debian'

# restart jenkins because of newer version
- name: restart jenkins
  command: (sleep 60 && service restart jenkins)&
  tags: after_config
