---
# file: roles/compute/tasks/main.yml

# migrate instances
- name: migrate instances
  script: migrate.sh {{ ansible_hostname }} {{ os_username }} {{ os_tenant_name }} {{ os_password }} {{ os_auth_url }}
  tags: before_config

# Stop Services
- name: stop services before upgrade
  service: name={{ item }} state=stopped
  with_items:
    - nova-compute
    - ceilometer-agent-compute
    - neutron-plugin-openvswitch-agent
  tags: before_config

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version=U14.04-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Ubuntu'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config

# Start Services
- name: start services after upgrade
  service: name={{ item }} state=started
  with_items:
    - nova-compute
    - ceilometer-agent-compute
    - neutron-plugin-openvswitch-agent
  tags: before_config

- name: allow instance scheduling on migrated compute
  command: nova-manage service enable --service nova-compute --host {{ ansible_hostname }}
  tags: before_config
