---
# file: roles/compute/tasks/main.yml

# Stop Services
- name: stop services before upgrade
  service: name={{ item }} state=stopped
  with_items:
    - nova-compute
    - ceilometer-agent-compute
    - neutron-plugin-openvswitch-agent
  tags: before_config

# Upgrade packages to Icehouse
- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version=U14.04-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Ubuntu'

- name: Restart the server
  shell: sleep 2s && reboot & executable=/bin/bash
  tags: before_config

- name: Wait until the machine stop
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} state=stopped
  sudo: false
  tags: before_config

- name: Wait for server to come up
  local_action: wait_for host={{ansible_ssh_host}} port={{ansible_ssh_port}} delay=60
  sudo: false
  tags: before_config

# Start Services
- name: start services after upgrade
  service: name={{ item }} state=started
  with_items:
    - nova-compute
    - ceilometer-agent-compute
    - neutron-plugin-openvswitch-agent
  tags: before_config
