---
# file: roles/full/tasks/main.yml
# this role is used when all services are running on the same node.

- name: migrate instances on another node
  script: migrate.sh {{ ansible_hostname }} {{ os_username }} {{ os_tenant_name }} {{ os_password }} {{ os_auth_url }}
  tags: before_config
  ignore_errors: yes

- name: stop services before upgrade
  service: name={{ item }} state=stopped
  tags: before_config
  with_items:
    - nova-compute
    - ceilometer-agent-compute
    - neutron-plugin-openvswitch-agent
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - ceilometer-api
    - ceilometer-collector
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - glance-api
    - glance-registry
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - keystone
    - neutron-server
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
    - nova-spicehtml5proxy
    - apache2
    - haproxy
    - keepalived
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version=14.04-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Ubuntu'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config

- name: ensure MySQL is running
  service: name=mysql state=started
  tags: before_config

- name: migrate keystone DB to UTF8
  script: keystone.sh
  tags: before_config
  when: inventory_hostname == groups['full'][-1]

- name: update keystone database
  command: keystone-manage db_sync
  tags: before_config
  when: inventory_hostname == groups['full'][-1]

- name: update nova database
  command: nova-manage db sync
  tags: before_config
  when: inventory_hostname == groups['full'][-1]

- name: migrate neutron DB to UTF8
  script: neutron.sh
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: migrate heat DB to UTF8
  script: heat.sh
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: migrate Glance DB to UTF8
  script: glance.sh
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: update glance database
  command: glance-manage db_sync
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: update cinder database
  command: cinder-manage db sync
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: update neutron database
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: update heat database
  command: heat-manage --config-file /etc/heat/heat.conf db_sync
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: restart services
  service: name={{ item }} state=restarted
  tags: before_config
  with_items:
    - nova-compute
    - ceilometer-agent-compute
    - neutron-plugin-openvswitch-agent
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - ceilometer-api
    - ceilometer-collector
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - glance-api
    - glance-registry
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - keystone
    - neutron-server
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-consoleauth
    - nova-scheduler
    - nova-spicehtml5proxy
    - apache2
    - keepalived
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: restart haproxy
  service: name=haproxy state=restarted
  tags: before_config
  ignore_errors: yes

- name: restart some services after database update
  service: name={{ item }} state=restarted
  with_items:
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - ceilometer-api
    - ceilometer-collector
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - glance-api
    - glance-registry
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - keystone
    - neutron-server
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-scheduler
    - nova-spicehtml5proxy
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - nova-compute
  tags: after_config

- name: restart services managed by pacemaker
  command: crm resource cleanup {{ item }}
  with_items:
    - ceilometer-agent-central
    - heat-engine
  tags: after_config
  when: inventory_hostname == groups['full'][-1]

- name: compress django horizon website
  command: /usr/share/openstack-dashboard/manage.py compress
  tags: after_config

- name: restart apache2
  service: name=apache2 state=restarted
  tags: after_config

- name: allow instance scheduling on migrated compute
  command: nova-manage service enable --service nova-compute --host {{ ansible_hostname }}
  tags: after_config
