---
# file: roles/network/tasks/main.yml

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name=sensu-client state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: restart neutron-plugin-openvswitch-agent after upgrade
  service: name=neutron-plugin-openvswitch-agent state=restarted
  tags: after_config
  when: ansible_distribution == 'Debian'

- name: restart neutron-l3-agent after upgrade
  service: name=neutron-l3-agent state=restarted
  tags: after_config
