---
# file: roles/network/tasks/main.yml

- name: stop services before upgrade
  service: name={{ item }} state=stopped
  tags: before_config
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-metering-agent

- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config

- name: ensure services are started after upgrade
  service: name={{ item }} state=started
  tags: before_config
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-metering-agent
