---
# file: roles/network/tasks/main.yml

- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: ensure services are restarted after upgrade
  service: name={{ item }} state=restarted
  tags: before_config
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-metering-agent
