---
# file: roles/network/tasks/main.yml

# We have to reboot all nodes since there is an upgrade in the kernel.
# So we have to migrate all routers of network nodes in migration to other L3 agents
# to avoid downtime.
- name: stop neutron-l3-agent before routers migration
  service: name=neutron-l3-agent state=stopped
  tags: before_config

- name: migrate routers on other L3 agent(s)
  script: migrate_routers.sh {{ os_username }} {{ os_tenant_name }} {{ os_password }} {{ os_auth_url }}
  tags: before_config

- name: stop services before upgrade
  service: name={{ item }} state=stopped
  tags: before_config
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-metering-agent

- name: edeploy upgrade
  edeploy: command=upgrade version=D7-{{ version }}
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config

- name: ensure services are started after upgrade
  service: name={{ item }} state=started
  tags: before_config
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-metering-agent
