---
# file: roles/load-balancer/tasks/main.yml

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

# HAproxy has been updated on Debian
# from 1.5.4-1 to 1.5.8-2
- name: restart HAproxy service
  service: name=haproxy state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'
