---
# file: roles/controller/tasks/main.yml

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

# Red Hat upgrade Galera to 25.3.5-5.el7ost
- name: restart
  service: name=mysqld state=restarted
  tags: before_config
  when: ansible_distribution == 'RedHat'

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name=sensu-client state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'
