---
# file: roles/controller/tasks/main.yml

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

# Red Hat upgrade Galera to 25.3.5-5.el7ost
- name: restart
  service: name=mysqld state=restarted
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: Wait for Galera VIP to come up
  local_action: wait_for host={{ galera_vip }} port=3306 delay=120 timeout=900 state=started
  tags: before_config
  when: ansible_distribution == 'RedHat'

# after upgrade, heat-api is zombie
- name: kill heat-api process
  command: pkill -9 heat-api
  tags: before_config
  when: ansible_distribution == 'Debian'

# then, restart it
- name: start heat-api service
  service: name=heat-api state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name=sensu-client state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: restart Cinder services after upgrade
  service: name={{ item }} state=restarted
  with_items:
    - openstack-cinder-api
    - openstack-cinder-volume
  tags: after_config
  when: ansible_distribution == 'RedHat'

- name: restart apache after upgrade
  service: name=httpd state=restarted
  tags: after_config
  when: ansible_distribution == 'RedHat'
