---
# file: roles/controller/tasks/main.yml

# RabbitMQ is upgraded in RHEL7
- name: stop rabbitmq
  service: name=rabbitmq-server state=stopped
  tags: before_config
  when: ansible_distribution == 'RedHat'

# MySQL is upgraded in RHEL7
# since we don't know if the node is master or not, we stop mysql anyway
- name: stop mysql
  service: name={{ item }} state=stopped
  with_items:
    - mysqld
    - mysql-boostrap
  tags: before_config
  ignore_errors: yes
  when: ansible_distribution == 'RedHat'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: start rabbitmq
  service: name=rabbitmq-server state=started
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['controller'][-1]

# Red Hat upgrade Galera to 25.3.5-5.el7ost
# since we start in serial mode one by one, we are sure here that the first node
# in the list will be master.
# For other nodes, they will be started by Puppet later.
- name: create systemd mysql-bootstrap script
  copy: src=mysql-bootstrap.service dest=/usr/lib/systemd/system/mysql-bootstrap.service
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['controller'][-1]

- name: reload systemd scripts list
  command: systemctl daemon-reload
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['controller'][-1]

- name: bootstrap mysql cluster again
  service: name=mysql-bootstrap state=restarted
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['controller'][-1]

# after upgrade, heat-api is zombie
- name: kill heat-api process
  command: pkill -9 heat-api
  tags: before_config
  when: ansible_distribution == 'Debian'

# then, restart it
- name: start heat-api service
  service: name=heat-api state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name=sensu-client state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: restart Cinder services after upgrade
  service: name={{ item }} state=restarted
  with_items:
    - openstack-cinder-api
    - openstack-cinder-volume
  tags: after_config
  when: ansible_distribution == 'RedHat'

- name: restart apache after upgrade
  service: name=httpd state=restarted
  tags: after_config
  when: ansible_distribution == 'RedHat'
