---
# file: roles/install-server/tasks/main.yml

# Dirty hack to upgade /usr/sbin/edeploy before actual upgrade
# and benefit of rsync with attributes feature.
# Useful when running SElinux before J.1.0.0
- name: upgrade edeploy script
  copy: src=edeploy dest=/usr/sbin/edeploy mode=0755
  tags: before_config

- name: stop Puppet
  service: name={{ item }} state=stopped
  with_items:
    - "{{ webserver }}"
    - puppetdb
    - postgresql
  tags: install_server

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: install_server

- name: Ensure old puppet ssl files are removed
  file: path=/var/lib/puppet/ssl state=absent
  tags: install_server

- name: Ensure old puppetdb configuration file are removed (puppetdb.conf and routes.yaml)
  file: path=/etc/puppet/{{ item }} state=absent
  with_items:
    - puppetdb.conf
    - routes.yaml
  tags: install_server

- name: Ensure old puppetdb configurations are removed from puppet.conf
  lineinfile: dest=/etc/puppet/puppet.conf state=absent regexp="\s*{{ item }}"
  with_items:
    - storeconfigs
    - reports
  tags: install_server

# We don't restart PuppetDB now, because it's managed by Puppet
# later, since we are running masterless setup now
- name: restart updated services
  service: name={{ item }} state=restarted
  with_items:
    - "{{ webserver }}"
    - redis
  tags: install_server
  when: ansible_distribution == 'RedHat'

# Ensure chroot is labelized
- name: SELinux labelized chroot
  shell: setfiles -r /var/lib/debootstrap/install/{{ distro }}-{{ version }}/openstack-full/ /etc/selinux/targeted/contexts/files/file_contexts /var/lib/debootstrap/install/{{ distro }}-{{ version }}/openstack-full/
  tags: install_server
  when: ansible_distribution == 'RedHat'

- name: kill old redis instance
  command: pkill -9 {{ redis }}
  tags: before_config

- name: restart redis
  service: name={{ redis }} state=restarted
  tags: after_config

- name: restart sensu
  service: name={{ item }} state=restarted
  with_items:
    - sensu-api
    - sensu-server
  tags: after_config
